In [131]:
import pandas as pd #Data 분석

In [132]:
df_train = pd.read_csv('data/감성분석/ratings_train.txt', sep='\t', encoding='UTF-8')

In [133]:
#DF 분석
df_train
df_train.info()
df_train.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

id          0
document    5
label       0
dtype: int64

In [134]:
#df_train의 'document'에서 null값을 제외하는 filt를 제외하고 출력
filt=df_train['document'].notnull()
df_train=df_train[filt]
df_train

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[149995 rows x 3 columns]

In [135]:
#긍정 부정 데이터값을 분석 가능
df_train['label'].value_counts()

label
0    75170
1    74825
Name: count, dtype: int64

In [136]:
#어떤 단어가 긍정 or 어떤 단어가 부정인지 분석하는 과정 수행(한글만 출력하기=정규식)
df_train.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [137]:
#한글만 출력하기 "정규식"(한글 외 ..., , 등 기호를 미리 제거하는 작업)
import re
pattern=r"[^가-힣]+" # raw데이터("r")가 가~힣(마지막 글자)까지가 아닌것(==한글이 아닌것)
df_train['document']=df_train['document'].apply(lambda x: re.sub(pattern,' ', x)) #re.sub >> x 가 pattern이 아닌 경우 공백으로 replcae 해주겠다
df_train.head()

         id                                           document  label
0   9976970                                  아 더빙 진짜 짜증나네요 목소리      0
1   3819312                       흠 포스터보고 초딩영화줄 오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                         교도소 이야기구먼 솔직히 재미는 없다 평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [138]:
#동일작업 df_test에 진행
df_test=pd.read_csv('data/감성분석/ratings_test.txt',sep='\t',encoding="UTF-8")
df_test.head()
df_test.isnull().sum()

filt=df_test['document'].notnull()
df_test=df_test[filt]
df_test.head()

df_test['document']=df_train['document'].apply(lambda x: re.sub(pattern,' ', x)) #re.sub >> x 가 pattern이 아닌 경우 공백으로 replcae 해주겠다
df_test.head()

        id                                           document  label
0  6270596                                  아 더빙 진짜 짜증나네요 목소리      1
1  9274899                       흠 포스터보고 초딩영화줄 오버연기조차 가볍지 않구나      0
2  8544678                                  너무재밓었다그래서보는것을추천한다      0
3  6825595                         교도소 이야기구먼 솔직히 재미는 없다 평점 조정      0
4  6723715  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      0

In [139]:
#전처리 데이터 저장하기
df_train.to_csv('data/감성분석/train.csv', index=False)
df_test.to_csv('data/감성분석/test.csv', index=False)

In [140]:
#백터화(문자를 숫자로 변환시켜주는 작업 수행), 문장에 어떤 단어의 빈도가 가장 많이 있는가?
from sklearn.feature_extraction.text import TfidfVectorizer
text = ['I go to my home my home is very large',
        'I went out my home I go to the market',
        'I bought a yellow lemon I go back to home']

In [141]:
#벡터 모델 만들기(괄호 내 조건 부여 가능)
tfidf=TfidfVectorizer(
    ngram_range=(1,2), # 단어 1개 and 단어 2 개의 단어도 백터를 줄 수 있음(3개짜리 단어 희망 시 (1,3))
    min_df=2, #횟수가 2회 이하의 백터들을 무시
    max_df=0.9# 상위 등장 90$는 제거
)

tfidf.fit(text)

TfidfVectorizer(max_df=0.9, min_df=2, ngram_range=(1, 2))

In [142]:
tfidf_text=tfidf.transform(text) #텍스트를 벡터화 한 결과를 tfidf_text에 넣음
tfidf_text #matrix, float 형식으로 변환됨
tfidf.vocabulary_.items() #데이터를 실제로 볼 수 있게 함
sorted(tfidf.vocabulary_.items()) #보기 편하게 줄바꿈해서 출력해줌 (현재 출력은 단어,1~2개 // 2회 이하 단어 제거 // 최상 90% 이상 단어는 제거)

[('go to', 0), ('my', 1), ('my home', 2)]

In [143]:
#한글 형태소 
from konlpy.tag import Okt
okt=Okt()

In [144]:
#한글 형태소 분석
def okt_tokenizer(text):
    tokens=okt.morphs(text)
    return tokens

text='즐거운추석명절을건강히잘보내세요!'
okt_tokenizer(text)

['즐거운', '추석', '명절', '을', '건강히잘', '보내세요', '!']

In [145]:
#벡터 모델 만들기(괄호 내 조건 부여 가능) 예제 2
tfidf=TfidfVectorizer(
    ngram_range=(1,2), # 단어 1개 and 단어 2 개의 단어도 백터를 줄 수 있음(3개짜리 단어 희망 시 (1,3))
    min_df=2, #횟수가 2회 이하의 백터들을 무시
    max_df=0.9# 상위 등장 90$는 제거
)

In [146]:
#실 데이터 적용
tfidf.fit(df_train['document'])
tfidf_train=tfidf.transform(df_train['document']) # document를 백터화 작업 수행

tfidf_train.shape

(149995, 118266)

In [147]:
df_train.shape
tfidf_train.shape

(149995, 118266)

In [148]:
# 모델생성(부정 or 긍정 check를 위헤 Rogistic 회귀모형 사용)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(C=1,max_iter=500,random_state=0) #C=규제강도, max_iter=반복 횟수
model.fit(tfidf_train,df_train['label'])

LogisticRegression(C=1, max_iter=500, random_state=0)

In [149]:
#모델학습
from sklearn.model_selection import GridSearchCV
parms={
    "C":[0.001,0.01,0.1,1,10],
    "max_iter":[50,100,150,200]
}

grid=GridSearchCV(model,param_grid=parms,scoring="accuracy", cv=3, verbose=1)

In [150]:
import warnings
warnings.filterwarnings('ignore')
grid.fit(tfidf_train,df_train['label'])

Fitting 3 folds for each of 20 candidates, totalling 60 fits

GridSearchCV(cv=3,
             estimator=LogisticRegression(C=1, max_iter=500, random_state=0),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10],
                         'max_iter': [50, 100, 150, 200]},
             scoring='accuracy', verbose=1)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
grid.fit(tfidf_train,df_train['label'])

In [151]:
grid.best_params_, grid.best_score_

({'C': 10, 'max_iter': 50}, 0.80983362483629)

In [152]:
best_model=grid.best_estimator_
train_pred=best_model.predict(tfidf_train)
train_pred[:50]

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1], dtype=int64)

In [153]:
df_train.head()
df_train['prediction']=train_pred
filt=df_train['label']==df_train['prediction']
df_equal=df_train[filt]

In [154]:
len(df_train), len(df_equal), len(df_equal)/len(df_train)

(149995, 132356, 0.8824027467582253)

In [157]:
df_test.head()

        id                                           document  label
0  6270596                                  아 더빙 진짜 짜증나네요 목소리      1
1  9274899                       흠 포스터보고 초딩영화줄 오버연기조차 가볍지 않구나      0
2  8544678                                  너무재밓었다그래서보는것을추천한다      0
3  6825595                         교도소 이야기구먼 솔직히 재미는 없다 평점 조정      0
4  6723715  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      0

In [ ]:
tfidf_test = tfidf.transform(df_test['document'])
test_pred=best_model.predict(tfidf_test)
df_test['prediction']=test_pred
df_test.head()

NotFittedError: The TF-IDF vectorizer is not fitted

In [ ]:
df_test.head()

        id                                           document  label
0  6270596                                  아 더빙 진짜 짜증나네요 목소리      1
1  9274899                       흠 포스터보고 초딩영화줄 오버연기조차 가볍지 않구나      0
2  8544678                                  너무재밓었다그래서보는것을추천한다      0
3  6825595                         교도소 이야기구먼 솔직히 재미는 없다 평점 조정      0
4  6723715  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      0

In [162]:

filt = df_test['label'] == df_test['prediction']
df_equal = df_test[filt]

KeyError: 'prediction'

In [163]:

len(df_test), len(df_equal), len(df_equal)/len(df_test)

(49997, 132356, 2.647278836730204)

In [ ]:
#백터화
tfidf_text=tfidf.transform(df_test['document'])

ValueError: np.nan is an invalid document, expected byte or unicode string.

In [ ]:
df_test['prediction']=test_grid
filt=df_test['label']==df_test['prediction']
df_equal=df_test[filt]

In [ ]:
len(df_test),len(df_grid),len(df_test)/len(df_gird)

In [ ]:
text='영화가 너무 재미있어요^^ 주인공들도 연기를 참 잘해요...'
find_text=re.findall(r"[가-힣]+",text)
find_text
text_join=[' '.join(find_text)]
tfidf_text=tfidf.transform(text_join)

In [164]:
def predict(text):
    find_text = re.findall(r'[가-힣]+', text)
    text_join = [' '.join(find_text)]
    tfidf_text = tfidf.transform(text_join)

    result=best_model.predict(tfidf_text)
    if result[0]==1:
        print('긍정')
    else:
        print('부정')

In [167]:
text='너무 욕심이 많았던 영화 어느 한 쪽만이라도 제대로 보여줬다면'
predict(text)
text='	지루하지는 않은데 완전 막장임... 돈주고 보기에는....'
predict(text)

NotFittedError: The TF-IDF vectorizer is not fitted

In [ ]:
result=best_model.predict(tfidf_text)
if result[0]==0:
    print('긍정')
else:
    print('부정')

부정

In [ ]:
def creat_model():
    #학습데이터 불러오기
    import pandas as pd
    df_train=pd.read_csv('data/감성분석/train.csv')
    df_train=df_train[:1000]
    df_train.head()

    # 한글 형태소의 분리함수
    from konlpy.tag  import Okt
    okt=Okt()
    def okt_tokenizer(text):
        tokens=okt.morphs(text)
        return tokens
        
    #document 백터화
    from sklearn.feature_extraction.text import TfidfVectorizer
    vector=TfidfVectorizer(tokenizer=okt_tokenizer,ngram_range=(1,2),min_df=3,max_df=0.9,token_pattern=None)

    vector.fit(df_train['document'])
    vector_trans=vector.transform(df_train['document'])

    #모델생성 후 모델학습
    from sklearn.linear_model import LogisticRegression
    model=LogisticRegression(C=10,max_iter=100)
    model.fit(vector_trans, df_train['label'])
    return vector,model

In [ ]:
import re
vector,model=creat_model()
text='8기 인공지능(AI) 기반 피싱 사이트 제작, 신규 일반 최상의 메인활동임'
find_text=re.findall(r'[가-힣]+',text)
text_join=[' '.join(find_text)]
vector_text=vector.transform(text_join)
pred=model.predict(vector_text)
print(pred) #영화데이터 기반 1은 긍정/0은 부정

[1]